apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: first-ns
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: first-ns
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gojo11/saurav-repo:2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: first-ns
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80